configName: mclv2_sam_rh707_pim
folderName: pmsm_foc_pll_estimator_rh707
format_version: v1.0
frameworkPath: ../../../../../../../../../Users/M43391/Harmony3Framework
processor: ATSAMRH707F18A
projectName: pmsm_foc_pll_estimator_rh707
settings:
  PackageFilter: bootloader;bootloader_apps_i2c;bsp;core;csp;csp_apps_pic32cm_jh00_jh01;csp_apps_pic32cm_le00_ls00;csp_apps_pic32cm_mc00;csp_apps_pic32cx_bz24_bz25;csp_apps_pic32mk;csp_apps_pic32mx;csp_apps_pic32mz_w1;csp_apps_sam_c20_c21;csp_apps_sam_d11;csp_apps_sam_d20;csp_apps_sam_d21_da1;csp_apps_sam_d5x_e5x;csp_apps_sam_e70_s70_v70_v71;csp_apps_sam_l10_l11;csp_apps_sam_l21;csp_apps_sam_l22;Devices;dev_packs;gfx;harmony-services;mc_apps_pic32cm_mc;mc_apps_pic32mk;mc_apps_sam_c2x;mc_apps_sam_d5x_e5x;mc_apps_sam_e7x_s7x_v7x;mc_apps_sam_rh707;mc_apps_sam_rh71;motor_control;net_apps_pic32mx;quick_docs;touch;validation;x2c
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMRH707_DFP\1.1.43\atdf\ATSAMRH707F18A.atdf
