package:
  format-version: "1.0.0"
  name: "mc_apps_sam_rh707"
  version: "v3.1.1"
  type: "application"
  status: "production"
  required: false

  dependencies:
    - name: "motor_control"
      type: "package"
      version: "fixed_point_dev_imprv"