configName: mclv2_sam_rh707_pim
folderName: pmsm_foc_pll_estimator_rh707
format_version: v1.0
frameworkPath: ../../../../../../../../../Users/M43391/Harmony3Framework
processor: ATSAMRH707F18A
projectName: pmsm_foc_pll_estimator_rh707
settings:
  PackageFilter: aerospace;bootloader;bsp;core;core_apps_sam_rh71;crypto;csp;csp_apps_sam_rh71;dev_packs;gfx;gfx_apps;harmony-services;mc_apps_pic32cm_mc;mc_apps_pic32mk;mc_apps_sam_c2x;mc_apps_sam_d5x_e5x;mc_apps_sam_e7x_s7x_v7x;mc_apps_sam_rh71;micrium_ucos3;motor_control;net;quick_docs;touch;usb;wireless;x2c;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMRH707_DFP\1.0.28\atdf\ATSAMRH707F18A.atdf
