format_version: v1.0
type: UniqueComponent
attributes: {id: X2CScope}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: X2C_SCOPE_PERIPH_USED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: X2CScope, value: FLEXCOM1_USART}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: x2cScopeUartDependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: flexcom1}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: FLEXCOM1_UART}
- type: ElementPosition
  attributes: {x: '294', y: '379', id: X2CScope}
